### ISSUE TITLE
Replace Theme Images with us!

### ISSUE THREAD

**Issue by DaKnOb** [devstaff-crete/devstaff.gr-website-static#11]
We may not look that good but we should use our images. We have plenty of them.

**Comment by gsaslis** [comment]
:+1: 

(@DaKnOb speak for yourself! :D )

**Comment by DaKnOb** [comment]
The solution to Women in Tech is to add my pictures to the site. You know it.. :P

**Comment by sonaht** [comment]
Closing this, since we are not "doing" anything. Re open if there is such need to seriously discuss this.

**Comment by papas-source** [comment]
👍
