### ISSUE TITLE
As per BeerUp #3 we should add Projects

### ISSUE THREAD

**Issue by DaKnOb** [devstaff-crete/devstaff.gr-website-static#12]
In the 3rd BeerUp we "decided" to add a "Projects" tab / page in the website (?) where we can showcase our Open Source work, either as individuals (?) or as DevStaff-Crete.

**Comment by gsaslis** [comment]
I guess this doesn't *have* to be on the website... 

tbh, i was just thinking of a simple .md in one of our github repos, so we don't have to worry about CSS and crap (there, I said it!)... 

Wouldn't something like the [Jobs Readme](https://github.com/devstaff-crete/DevStaff-Heraklion/blob/master/jobs/README.md) be ok ?

**Comment by DaKnOb** [comment]
Ah, okay.. We never discussed the implementation. I guess this works as well.. :P

**Comment by gsaslis** [comment]
https://github.com/devstaff-crete/DevStaff-Heraklion/pull/68 ; )

**Comment by sonaht** [comment]
Ok closing this

Projects exist now on this:

https://github.com/devstaff-crete/DevStaff-Heraklion/tree/master/projects
