### ISSUE TITLE
Nav menu somewhat broken on mobile

### ISSUE THREAD

**Issue by gsaslis** [devstaff-crete/devstaff.gr-website-static#45]
![26bf0545-90bb-4a3a-b958-e36ae8a3c838](https://user-images.githubusercontent.com/2420882/39981807-cdb06c6a-575a-11e8-97c7-547ff19da600.png)

Second row shows up outside of white area

**Comment by gsaslis** [comment]
@mzampetakis this sth u can help out with?

**Comment by mzampetakis** [comment]
@gsaslis fixed by  #46 .
