### ISSUE TITLE
Remove Facebook link for each event

### ISSUE THREAD

**Issue by mzampetakis** [devstaff-crete/devstaff.gr-website-static#86]
I think we should remove the facebook icon/link from each event. We cannot post links to every social media we hold for each event.

Let's just hold the meetup link and the GitHub folder of the specific meetup.

**Comment by kouts** [comment]
Should we remove the relevant data or just comment out the fb icon/link from the template?

**Comment by mzampetakis** [comment]
Probably both @kouts . It's not a bit deal after all.
